seed: 42

d_model: 256 
d_emb: 8 
k: 16

data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot
meta_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/data/metadata

datamodule: 
  _target_: data.discover.datamodule.MimicGenRobotDataModule

  data_dir: ${data_dir}
  meta_dir: ${meta_dir}

  robots: null # iiwa, panda, sawyer, ur5e
  tasks: null # square, threading
  n_ds: 1 # {1, 2} if d_0 or d_0 & d_1
  f_ds: 0.1
  depth: False # True: include depth maps  
  crop_factor: 0.75 # (0, 1)
  noise_level: 0.1 # (0, 1)
  window: 8 # > 0
  chunk: 1 # > 0

  batch_size: 2
  shuffle: True
  num_workers: 31
  pin_memory: True
  persistent_workers: True 
  dataset_lengths: 
  - 0.8
  - 0.1
  - 0.1

  seed: ${seed}

  transforms: 
    - to_image
    - resize
    - gaussian_blur
    - color_jitter 
    - rotate 
    - to_dtype
    - solarize
    - normalize

model: 
  _target_: models.discover.tse.TSE
  
  vision_backbone_kwargs: 
    model: resnet50
    weights_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights
    lora: True
    layer: 
      - 4 
    r: 8
    lora_alpha: 1
    lora_drop_out: 0.0

  vision_encoder_kwargs: 
    encoder_layer_kwargs: 
      d_model: ${d_model}
      nhead: 4 
      dim_feedforward: 512
      batch_first: True

    transformer_encoder_kwargs:
      num_layers: 8
      norm: null
      enable_nested_tensor: False 
      mask_check: False

    down_emb_kwargs: 
      in_features: 1000 
      out_features: ${d_model}
    
    up_emb_kwargs:
      in_features: ${d_model}
      hidden_features: 32
      out_features: ${d_emb} 
      
    pe_kwargs: 
      d_model: ${d_model}
      max_len: 300
  
  vic_reg_kwargs: 
    lambda_: 25
    mu: 25
    nu: 1
    gamma: 1
    epsilon: 1e-4

  skill_head_kwargs: 
    in_features: ${d_model}
    out_features: ${k}
    bias: False
  
  tsne_kwargs: 
    n_components: 2 
    learning_rate: auto 
    init: random 
    perplexity: 3
    random_state: ${seed}
  
  sinkhorn_kwargs: 
    tau: 0.1
    sinkhorn_iterations: 3 
    epsilon: 0.1
  
  optimizer_kwargs: 
    optimizer: 
      lr: 1e-3
    lr_scheduler: 
      T_max: null
      eta_min: 0

logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  name: train
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_discovery

trainer: 
  _target_: lightning.pytorch.Trainer

  accelerator: gpu   
  # strategy: ddp # delete to run on single gpu
  devices: # for ddp: -1 
    - 0 # single gpu 
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_discovery/