seed: 42
data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot
meta_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/data/metadata

data: 
  datamodule: 
    _target_: data.discover.datamodule.MimicGenRobotDataModule
    data_dir: ${data_dir}
    meta_dir: ${meta_dir}
    window: 8 
    robots: panda
    tasks: threading
    expand_depth: colormap 

    batch_size: 80
    shuffle: True
    num_workers: 31 
    pin_memory: True
    drop_last: True
    persistent_workers: True 
    multiprocessing_context: None # prevents fork deadlocks in CUDA DDP
    dataset_lengths: 
    - 0.8
    - 0.1  
    - 0.1 

    transforms: 
      - grayscale
      - gaussian_blur
      - color_jitter 
      - solarize
      - rotate 

model: 
  _target_: models.discover.discover.SkillDiscovery

  vision_backbone_kwargs: 
    weights_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/resNet18_Weights_DEFAULT.pth
  
  vision_encoder_kwargs: 
    encoder_layer_kwargs: 
      d_model: 500 
      nhead: 1 
      dim_feedforward: 1024
    transformer_encoder_kwargs:
      num_layers: 1
    
  gmm_kwargs: 
    k: 20 
    d: ${model.vision_encoder_kwargs.encoder_layer_kwargs.d_model}
    alpha: 0.1
    beta: 0.2
    sim: 
      dim: 1.0
      eps: 1.0e-6
    weights: ~
    means: ~
    covs: ~
  
  optimizer_kwargs: 
    optimizer: 
      lr: 1e-3
    lr_scheduler: 
      start_factor: 0.5 
      total_iters: 40 

logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  name: debugging
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_discovery

trainer: 
  accelerator: gpu   
  # strategy: ddp # delete to run on single gpu
  devices: 0 # -1
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_discovery/

TSNE: 
  n_components: 2 
  perplexity: 25
  learning_rate: auto
  init: pca