seed: 42

data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot
meta_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/data/metadata

d_model: 256
k: 16
d_emb: 8 

datamodule: 
  _target_: data.discover.datamodule.MimicGenRobotDataModule

  data_dir: ${data_dir}
  meta_dir: ${meta_dir}
  window: 8 
  chunk: 10
  crop_factor: 0.75
  noise_level: 0.1
  robots: # has to be a list or null!
    - iiwa
    # - panda 
    # - sawyer 
    # - ur5e
  tasks: # has to be a list or null!
    # - square
    - threading 
  depth: False
  batch_size: 4
  shuffle: True
  num_workers: 31
  pin_memory: True
  persistent_workers: True 
  # multiprocessing_context: "forkserver" # prevents fork deadlocks in CUDA DDP
  
  dataset_lengths: 
  - 0.8
  - 0.1
  - 0.1

  transforms: 
    - to_image
    - resize
    - gaussian_blur
    - color_jitter 
    - rotate 
    - to_dtype
    - solarize
    - normalize

model: 
  _target_: models.discover.tse.TSE
  # _target_: models.discover.tse_new.TSE
  
  # gripper_up_kwargs: 
  #   in_features: 1 
  #   out_features: ${d_model}


  # vision_backbone_kwargs: 
  #   weights_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/r3m_resnet18_weights.pth
    
  vision_encoder_kwargs: 
    encoder_layer_kwargs: 
      d_model: ${d_model}
      nhead: 1 
      dim_feedforward: 512

    transformer_encoder_kwargs:
      num_layers: 2
      norm: null
      enable_nested_tensor: False 
      mask_check: False

    down_emb_kwargs: 
      in_features: 1000 
      out_features: ${d_model}
    
    up_emb_kwargs:
      in_features: ${d_model}
      hidden_features: 32
      out_features: ${d_emb} 
      
    pe_kwargs: 
      d_model: ${d_model}
      max_len: 300

  cluster_head_kwargs: 
    in_features: ${d_model}
    out_features: ${k}
    bias: False

  vic_reg_kwargs: 
    lmb: 25
    mu: 25
    nu: 1
    gamma: 1
    eps: 1e-4
  
  sinkhorn_kwargs: 
    sinkhorn_iterations: 3 
    epsilon: 0.1

  
  # kmeans_kwargs: 
  #   k: 4 
  #   d: ${d_emb}
  #   max_iter: 200 
  #   rtol: 1e-4

  # rgmm_kwargs: 
  #   k: ${model.kmeans_kwargs.k}
  #   d: ${model.vision_encoder_kwargs.out_kwargs.out_features}
  #   jitter_noise: 1e-6
  #   shift_scale: 1.1 
  #   shift_bias: 1e-5
  #   max_iter: 200
  #   bml_weight: 1e-4
  #   bml_alpha: 0.2
  #   bml_beta: 0.5
  #   sim: 
  #     dim: 1
  #     eps: 1.0e-6

  optimizer_kwargs: 
    optimizer: 
      lr: 1e-3
    lr_scheduler: 
      start_factor: 0.5 
      total_iters: 40 

logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  name: train
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_discovery

trainer: 
  accelerator: gpu   
  # strategy: ddp # delete to run on single gpu
  devices: # for ddp: -1 
    - 0 # single gpu 
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_discovery/