defaults: 
  - base 
  - _self_ 

datamodule: 
  robots: 
    - iiwa 
    - panda 
  tasks:
    - square

  window_size: 4 # > 0
  batch_size: 128
  
  transforms: # r3m model expects unnormalized images with pixel values in [0, 255]
    - to_image
    - rotate 
    - resize_r3m
    - color_jitter
    - grayscale 
    - to_dtype_r3m

model_vision: 
  _target_: models.fine_tune.fine_tuner.FineTunerVisual
  _recursive_: False

  optimizer_kwargs: 
    encoder: 
      lr: 1e-3
      weight_decay: 1e-3
    expander: 
      lr: 1e-4
      weight_decay: 1e-4

  scheduler_kwargs: 
    warmup_percentage: 0.1
    linear:  
      start_factor: 1e-4
      end_factor: 1.0 
      total_iters: null # adapted dynamically  
    cosine_annealing: 
      T_max: null # adapted dynamically 
      eta_min: 1e-5
  
  vision_encoder_kwargs: 
    model_name: resnet18
    d_model: ${d_model}
    start_layer: 3 # {3, 4}
  
    r: 64
    lora_alpha: 128
    lora_dropout: 0.05
    bias: lora_only

  expander_kwargs: 
    in_dim: ${d_model}
    h_dim: ${eval:"${d_model}*2"}
    out_dim: ${eval:"${d_model}*4"}
    batch_norm_kwargs: 
      momentum: 0.1 

  vic_reg_kwargs: 
    log_every_n_steps: 50 

    lambda_: 0.005
    mu: 2
    nu: 0.05
    gamma: 1
    eps: 1e-4

logger: 
  name: new_try
  project: fine_tune

callbacks: 
  learning_rate_monitor: 
    _target_: lightning.pytorch.callbacks.LearningRateMonitor 
    logging_interval: step 

  model_checkpoint: 
    monitor: val/tot_loss