defaults: 
  - base 
  - _self_ 

datamodule: 
  robots: 
    - iiwa 
    - panda 
  tasks:
    - square
  
  transforms: # r3m model expects unnormalized images with pixel values in [0, 255]
    - to_image
    - resize_r3m
    - to_dtype_r3m

model_vision: 
  _target_: models.fine_tune.fine_tuner.FineTunerVisual
  _recursive_: False

  optimizer_kwargs: 
    encoder: 
      lr: 1e-4
      weight_decay: 1e-3

    expander: 
      lr: 1e-5
      weight_decay: 1e-4

  scheduler_kwargs: 
    warmup_percentage: 0.1

    linear:  
      start_factor: 1e-4
      end_factor: 1.0 
      total_iters: 100 # adapted dynamically  

    cosine_annealing: 
      T_max: 1000 # adapted dynamically 
      eta_min: 1e-6
  
  vision_encoder_kwargs: 
    model_name: resnet18
    d_model: ${d_model}
  
    r: 64
    lora_alpha: 64
    lora_dropout: 0.05
    bias: lora_only

  expander_kwargs: 
    in_dim: ${d_model}
    h_dim: ${eval:"${d_model}*1"}
    out_dim: ${eval:"${d_model}*1"}

  vic_reg_kwargs: 
    log_every_n_steps: 50 

    lambda_: 15.0
    mu: 35.0
    nu: 10.0
    gamma: 1.0
    eps: 1e-4

logger: 
  name: new_try
  project: fine_tune

callbacks: 
  learning_rate_monitor: 
    _target_: lightning.pytorch.callbacks.LearningRateMonitor 
    logging_interval: step 

  model_checkpoint: 
    monitor: val/tot_loss