seed: 42

d_model: 256 

data_dir: /dss/dssfs04/lwp-dss-0002/pn36ce/pn36ce-dss-0000/ehrensberger/imports/mimicgen/datasets/robot
meta_dir: /dss/dssfs04/lwp-dss-0002/pn36ce/pn36ce-dss-0000/ehrensberger/master-thesis/data/metadata

datamodule: 
  _target_: data.discover.datamodule.MimicGenRobotDataModule

  data_dir: ${data_dir}
  meta_dir: ${meta_dir}

  robots: null # iiwa, panda, sawyer, ur5e
  tasks: null # square, threading
  n_ds: 1 # {1, 2} if d_0 or d_0 & d_1
  f_ds: 1
  depth: False # True: include depth maps  
  crop_factor: 0.75 # (0, 1)
  noise_level: 0.1 # (0, 1)
  window: 16 # > 0
  chunk: 1 # > 0

  batch_size: 16
  shuffle: True
  num_workers: 0
  pin_memory: True
  persistent_workers: True 
  dataset_lengths: 
  - 0.8
  - 0.1
  - 0.1

  seed: ${seed}
  
  ctr_transforms: False # transforms reuquired for constrastive learning
  transforms: 
    - to_image
    - resize
    - to_dtype
    - normalize

model: 
  _target_: models.01_fine_tune.fine_tuner.FineTuner
  _recursive_: False
  
  optimizer_kwargs: 
    _target_: torch.optim.SGD
    _recursive_: False
    lr: 1e-3
    momentum: 0.9
    weight_decay: 1e-4

  scheduler_kwargs: 
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _recursive_: False
    T_max: 0 # placeholder -> all steps  
    eta_min: 1e-6

  vision_encoder_kwargs: 
    model: resnet50
    lora: True
    layer: 
      - 4 
    r: 16
    lora_alpha: 16
    lora_drop_out: 0.05

    out_emb_kwargs: 
      in_features: 2048 
      out_features: ${d_model}

  gripper_encoder_kwargs: 
    in_features: 128 
    out_features: ${d_model}

  expander_kwargs: 
    in_dim: ${d_model}
    h1_dim: 64
    h2_dim: 128
    out_dim: ${d_model}

  vic_reg_kwargs: 
    lambda_: 25.0
    mu: 25.0
    nu: 1.0
    gamma: 1.0
    epsilon: 1e-4
  
  dwa_kwargs: 
    n_losses: 2
    T: 2
  
logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  name: rgb_2_depth_0_gripper_ds_1
  version: ${now:%Y_%m_%d_%H_%M}
  project: fine_tune

trainer: 
  _target_: lightning.pytorch.Trainer
  accelerator: gpu   
  devices: 
    - 0
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_discovery/