seed: 42

d_model: 256 
d_emb: 8 
k: 10

data_dir: /dss/dssfs04/lwp-dss-0002/pn36ce/pn36ce-dss-0000/ehrensberger/imports/mimicgen/datasets/robot
meta_dir: /dss/dssfs04/lwp-dss-0002/pn36ce/pn36ce-dss-0000/ehrensberger/master-thesis/data/metadata

datamodule: 
  _target_: data.discover.datamodule.MimicGenRobotDataModule

  data_dir: ${data_dir}
  meta_dir: ${meta_dir}

  robots: null # iiwa, panda, sawyer, ur5e
  tasks: null # square, threading
  n_ds: 2 # {1, 2} if d_0 or d_0 & d_1
  f_ds: 1
  depth: False # True: include depth maps  
  crop_factor: 0.75 # (0, 1)
  noise_level: 0.1 # (0, 1)
  window: 8 # > 0
  chunk: 8 # > 0

  batch_size: 16
  shuffle: True
  num_workers: 31
  pin_memory: True
  persistent_workers: True 
  dataset_lengths: 
  - 0.8
  - 0.1
  - 0.1

  seed: ${seed}
  
  ctr_transforms: False
  transforms: 
    - to_image
    - resize
    - to_dtype
    - normalize

model: 
  _target_: models.discover.pretrain.Pretrain
  _recursive_: False
  
  optimizer_kwargs: 
    _target_: torch.optim.SGD
    _recursive_: False
    lr: 1e-3

  scheduler_kwargs: 
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _recursive_: False
    T_max: 0 # placeholder 
    eta_min: 0

  vision_backbone_kwargs: 
    model: resnet50
    lora: True
    layer: 
      - 4 
    r: 8
    lora_alpha: 1
    lora_drop_out: 0.0

  vision_encoder_kwargs: 
    encoder_layer_kwargs: 
      d_model: ${d_model}
      nhead: 4 
      dim_feedforward: 512
      batch_first: True

    transformer_encoder_kwargs:
      num_layers: 8
      norm: null
      enable_nested_tensor: False 
      mask_check: False

    down_emb_kwargs: 
      in_features: 2048 
      out_features: ${d_model}
    
    up_emb_kwargs:
      in_features: ${d_model}
      hidden_features: 32
      out_features: ${d_model} 
      
    pe_kwargs: 
      d_model: ${d_model}
      max_len: 300
  
  gripper_backbone_kwargs: 
    in_features: 1 
    out_features: ${d_model}
  
  gripper_encoder_kwargs: 
    encoder_layer_kwargs: 
      d_model: ${d_model}
      nhead: 1
      dim_feedforward: 512
      batch_first: True

    transformer_encoder_kwargs:
      num_layers: 2
      norm: null
      enable_nested_tensor: False 
      mask_check: False
      
    pe_kwargs: 
      d_model: ${d_model}
      max_len: 300

  vic_reg_kwargs: 
    lambda_: 25
    mu: 25
    nu: 1
    gamma: 1
    epsilon: 1e-4
  
logger: 
  _target_: lightning.pytorch.loggers.WandbLogger
  name: train
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_discovery

trainer: 
  _target_: lightning.pytorch.Trainer
  accelerator: cpu   
  devices: 1 
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_discovery/