seed: 42 
data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot/
meta_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/data/metadata
cfgs_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/cfgs/dh_cfgs/

stage: fit # test, predict

datamodule: 
  _target_: data.transfer.datamodule.TransferDataModule 
  
  data_dir: ${data_dir}
  meta_dir: ${meta_dir}
  cfgs_dir: ${cfgs_dir}
  horizon: 16 
  crop_factor: 0.75
  robots: # has to be a list or null
    # - iiwa
    - panda 
    # - sawyer 
    # - ur5e
  tasks: # has to be a list or null 
    # - square
    - threading 
  depth: False
  batch_size: 2
  shuffle: True
  num_workers: 1
  pin_memory: True 
  drop_last: True
  persistent_workers: True 

  dataset_lengths: 
  - 0.8 
  - 0.1 
  - 0.1

  transforms: 
    - to_image 
    - resize 
    - to_dtype 
    - normalize 
  
model: 
  _target_: models.transfer.sad.SAD

  d_model: 256
  obs_encoder_ckpt: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/r3m_resnet18_weights.pth
  
  tse_ckpt: null 
  
  rce_kwargs:
    dsc_kwargs: 
      input_dim: 3
      hidden_dim: 64
      output_dim: 32

    obs_kwargs: 
      input_dim: 2
      output_dim: 32

    h_kwargs: 
      tau: 0.1
      tau_min: 0.01
      epsilon: 1e-6

  dit_kwargs:
    d_model: ${model.d_model}
    action_dim: 7  
    obs_emb_dim: ${model.d_model} 
    action_horizon: 16 

    noise_scheduler_kwargs: 
      num_train_timesteps:  100 

    decoder_layer_kwargs: 
      d_model: ${model.d_model} 
      nhead: 2 
      dim_feedforward: 1024
      batch_first: True

    transformer_decoder_kwargs: 
      num_layers: 2 

    pe_kwargs: 
      d_model: ${model.sat_kwargs.encoder_layer_kwargs.d_model}
      max_len: 300

  sat_kwargs: 
    weights_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/r3m_resnet18_weights.pth

    encoder_layer_kwargs: 
      d_model: 256 
      nhead: 4 
      dim_feedforward: 512 

    transformer_encoder_kwargs: 
      num_layers: 1
  
    pe_kwargs: 
      d_model: ${model.sat_kwargs.encoder_layer_kwargs.d_model}
      max_len: 300
    
  optimizer_kwargs: 
    optimizer: 
      lr: 1e-3
    lr_scheduler: 
      start_factor: 0.5 
      total_iters: 40 
  
logger: 
  _target_: lightning.pytorch.loggers.WandbLogger

  name: debugging
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_transfer

trainer: 
  accelerator: gpu   
  # strategy: ddp # delete to run on single gpu
  devices: # for ddp: -1 
    - 0 # single gpu 
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_transfer/