seed: 42 
data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot/

stage: fit # test, predict

datamodule: 
  _target_: data.transfer.datamodule.TransferDataModule 
  
  data_dir: ${data_dir}
  horizon: 8 
  robots: 
    # - iiwa
    - panda 
    # - sawyer 
    # - ur5e
  tasks: 
    # - square
    - threading 
  depth: False
  cfgs_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/cfgs/dh_cfgs/
  batch_size: 8 
  shuffle: True
  num_workers: 31
  pin_memory: True 
  drop_last: True 
  persistent_workers: True 
  dataset_lengths: 
  - 0.8 
  - 0.1 
  - 0.1
  
model: 
  _target_: models.transfer.transfer.SkillTransfer
 
  ditbc_kwargs: 
    action_dim: 512
    obs_dim: 512 
    horizon: 16 
    hidden_dim: 2048 
    num_heads: 4 
    num_layers: 4 
    num_timesteps: 100 
    deivce: ~

  rce_kwargs:
    dsc_kwargs: 
      input_dim: 512
      hidden_dim: 128
      output_dim: 32
    obs_kwargs: 
      input_dim: 512
      output_dim: 128
    h_kwargs: 
      tau: 0.1
      tau_min: 0.01
      epsilon: 1e-6

  sat_kwargs: 
    d_model: 5 
    n_head: 4 
    dim_feedforward: 512 

  optimizer_kwargs: 
    optimizer: 
      lr: 1e-3
    lr_scheduler: 
      start_factor: 0.5 
      total_iters: 40 
  
  tse_ckpt: "hello"

logger: 
  _target_: lightning.pytorch.loggers.WandbLogger

  name: debugging
  version: ${now:%Y_%m_%d_%H_%M}
  project: skill_transfer

trainer: 
  accelerator: gpu   
  # strategy: ddp # delete to run on single gpu
  devices: # for ddp: -1 
    - 0 # single gpu 
  max_epochs: 400 
  num_sanity_val_steps: 2
  enable_progress_bar: True
  profiler: simple 
  default_root_dir: logs/skill_transfer/