_wandb:
    value:
        cli_version: 0.26.1
        e:
            wx9uacb4bammf97mq22z5tjynv96z5r0:
                codePath: skill_discovery.py
                codePathLocal: skill_discovery.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "942429499392"
                        used: "203241627648"
                email: andreas.ehrensberger@tum.de
                executable: /home/bing_TUM/ehrensberger/master-thesis/sim/bin/python3
                git:
                    commit: 10e8b980952016af3635ae3e77d87c923406d59c
                    remote: https://andreas00e:@github.com/andreas00e/master-thesis.git
                gpu: Tesla V100-PCIE-32GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-af370d4d-1cd7-7674-a75f-8d83ecec6959
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-be8d966c-6293-2be3-dfdc-d03e40ffdd12
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-deda47f4-3dbc-2542-52d2-6659ff78d272
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-c2307c63-9bc5-3414-60c7-a481da76651a
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-d9d83365-c6d3-b5b6-1e54-2dc99148454c
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-3b49b182-1e25-325c-e5c2-aca3c2c3d756
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-345ff00e-d3c8-3dd2-31ce-82fe1a0000c2
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-PCIE-32GB
                      uuid: GPU-08192335-93e6-7441-1802-857184ac1107
                host: S49
                memory:
                    total: "270093410304"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.31
                program: /home/bing_TUM/ehrensberger/master-thesis/thesis/skill_discovery.py
                python: CPython 3.11.5
                root: .
                startedAt: "2026-07-23T13:04:15.034800Z"
                writerId: wx9uacb4bammf97mq22z5tjynv96z5r0
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 106
            "3":
                - 7
                - 13
                - 14
                - 41
                - 66
            "4": 3.11.5
            "5": 0.26.1
            "6": 4.41.2
            "12": 0.26.1
            "13": linux-x86_64
gmm_kwargs:
    value: '{''k'': 20, ''d'': 4, ''alpha'': 0.1, ''beta'': 0.2, ''sim'': {''dim'': 1, ''eps'': 1e-06}, ''weights'': None, ''means'': None, ''covs'': None}'
vision_backbone_kwargs:
    value: '{''weights_path'': ''/home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/resNet18_Weights_DEFAULT.pth''}'
vision_encoder_kwargs:
    value: '{''encoder_layer_kwargs'': {''d_model'': 500, ''nhead'': 1, ''dim_feedforward'': 1024}, ''transformer_encoder_kwargs'': {''num_layers'': 1}}'
