seed: 42
data_dir: /home/bing_TUM/ehrensberger/master-thesis/imports/mimicgen/datasets/robot
meta_dir: /home/bing_TUM/ehrensberger/master-thesis/thesis/data/metadata

data: 
  datamodule: 
    file_dir: ${data_dir}
    meta_dir: ${meta_dir}
    robots: ~
    tasks: 
      - stack
    horizon: 10 
    depth: False
    expand_depth: colormap 

    batch_size: 16
    shuffle: False
    num_workers: 32 
    pin_memory: True
    persistent_workers: True    

model: 
  weights_path: /home/bing_TUM/ehrensberger/master-thesis/thesis/models/weights/resNet18_Weights_DEFAULT.pth

trainer: 
  devices: 
    - 0
  default_root_dir: logs 
  max_epochs: 400 
  profiler: simple 
  reload_dataloaders_ever_n_epochs: 1 

TSNE: 
  n_components: 2 
  perplexity: 25
  learning_rate: "auto"
  init: "pca"
